# Generated by Django 5.2.8 on 2025-11-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0004_ourteam"),
    ]

    operations = [
        migrations.AddField(
            model_name="ourteam",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
